apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-file-handler
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bff-file-handler
  template:
    metadata:
      labels:
        app: bff-file-handler
    spec:
      containers:
      - name: bff-file-handler
        image: bff-file-handler:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: "0.2"
            memory: 200Mi
          requests:
            cpu: "0.2"
            memory: 100Mi
